const ABSTRACT_BLACK = '#000000';
const ABSTRACT_GLAY = '#999999';
const ABSTRACT_WHITE = '#ffffff';
const ABSTRACT_NAVY = '#114086';

export const Colors = {
  UI_BASE: ABSTRACT_BLACK,
  UI_TEXT_MAIN: ABSTRACT_BLACK,
  UI_TEXT_SUB: ABSTRACT_GLAY,
  UI_TEXT_DARK_BACKGROUND: ABSTRACT_WHITE,
  UI_LINE_NORMAL: ABSTRACT_BLACK,
  UI_LINE_WEAKEN: ABSTRACT_GLAY,
  ABSTRACT_BLACK,
  ABSTRACT_GLAY,
  ABSTRACT_WHITE,
  ABSTRACT_NAVY,
  TRANSPRENT: 'transparent',
} as const;

export default Colors;
